# Generated by Django 5.1.4 on 2025-01-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_alter_post_author'),
    ]

    operations = [
    ]
